{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels:
    {{- include "menherabot.labels" . | nindent 4 }}
  annotations:
    {{- toYaml .Values.ingress.annotations | nindent 4 }}
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.global.domain }}
      http:
        paths:
          {{- if .Values.api.enabled }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: {{ include "menherabot.api.fullname" . }}
                port:
                  number: {{ .Values.api.service.port }}
          {{- end }}
          {{- if .Values.web.enabled }}
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "menherabot.web.fullname" . }}
                port:
                  number: {{ .Values.web.service.port }}
          {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    - hosts:
        - {{ .Values.global.domain }}
  {{- end }}
{{- end }}
